<a href="https://colab.research.google.com/github/Tanzeela00Sharif/python-notebooks-collection/blob/main/MultiIndex_Objects.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#creation of series
index_val=[('cse',2019),('cse',2020),('cse',2021),('cse',2022),('cse',2023),('cse',2024)]
a=pd.Series([1,2,3,4,5,6,],index=index_val)

In [ ]:
#problem with series
#index work as tuple
#a[('cse')]

##way to create multiindx data

In [ ]:
1. #pd.MultiIndex.from_tuples
index_val=[('cse',2019),('cse',2020),('cse',2021),('cse',2022),('cse',2023),('cse',2024)]
a=pd.MultiIndex.from_tuples(index_val)
a.levels

FrozenList([['cse'], [2019, 2020, 2021, 2022, 2023, 2024]])

In [ ]:
2. #pd.MultiIndex.from_product
MultiIndex=pd.MultiIndex.from_product([['cse','ece'],[2012,2013,2014,2015]])

In [ ]:
#creating series with multiindex
a=pd.Series([1,2,4,5,6,7,8,9],index=MultiIndex)
a

cse  2012    1
     2013    2
     2014    4
     2015    5
ece  2012    6
     2013    7
     2014    8
     2015    9
dtype: int64

In [ ]:
#how to fetch items from such series
a[('ece',2012)]
a['cse']

2012    1
2013    2
2014    4
2015    5
dtype: int64

In [ ]:
temp=a.unstack()

In [ ]:
temp.unstack()

2012  cse    1
      ece    6
2013  cse    2
      ece    7
2014  cse    4
      ece    8
2015  cse    5
      ece    9
dtype: int64

In [ ]:
#multiindex data frame
multi_df=pd.DataFrame(
    [
      [1,2],
      [3,4],
      [5,6],
      [7,8],
      [9,10],
      [11,12],
      [13,14],
      [15,16]
    ],
    index=MultiIndex,
    columns=['avg_pakage','students']
    )

In [ ]:
multi_df

          avg_pakage  students
cse 2012           1         2
    2013           3         4
    2014           5         6
    2015           7         8
ece 2012           9        10
    2013          11        12
    2014          13        14
    2015          15        16

In [ ]:
#fetch data
multi_df.loc['ece']

      avg_pakage  students
2012           9        10
2013          11        12
2014          13        14
2015          15        16

In [ ]:
multi_df['avg_pakage']

cse  2012     1
     2013     3
     2014     5
     2015     7
ece  2012     9
     2013    11
     2014    13
     2015    15
Name: avg_pakage, dtype: int64

In [ ]:
b=pd.DataFrame(
    [
    [1,2,3,5],
    [6,7,8,9],
    [16,17,18,19],
    [20,21,22,23]
    ],
    index=[2023,2024,2025,2026],
    columns=MultiIndex.from_product([['karachi','lahore'],['avg_pakage','students']])
    )

In [ ]:
b['lahore']['avg_pakage']

2023     3
2024     8
2025    18
2026    22
Name: avg_pakage, dtype: int64

In [ ]:
b

        karachi              lahore
     avg_pakage students avg_pakage students
2023          1        2          3        5
2024          6        7          8        9
2025         16       17         18       19
2026         20       21         22       23

In [ ]:
MultiIndex

MultiIndex([('cse', 2012),
            ('cse', 2013),
            ('cse', 2014),
            ('cse', 2015),
            ('ece', 2012),
            ('ece', 2013),
            ('ece', 2014),
            ('ece', 2015)],
           )

In [ ]:
b.loc[2023]

karachi  avg_pakage    1
         students      2
lahore   avg_pakage    3
         students      5
Name: 2023, dtype: int64

In [ ]:
b=pd.DataFrame(
    [
    [1,2,3,5],
    [6,7,8,9],
    [16,17,18,19],
    [20,21,22,23],
    [16,17,18,19],
    [20,21,22,23],
    [21,23,23,43],
    [43,54,34,67]
    ],
    index=MultiIndex,
    columns=MultiIndex.from_product([['karachi','lahore'],['avg_pakage','students']])
    )

In [ ]:
b

            karachi              lahore
         avg_pakage students avg_pakage students
cse 2012          1        2          3        5
    2013          6        7          8        9
    2014         16       17         18       19
    2015         20       21         22       23
ece 2012         16       17         18       19
    2013         20       21         22       23
    2014         21       23         23       43
    2015         43       54         34       67

In [ ]:
b.loc['cse']

        karachi              lahore
     avg_pakage students avg_pakage students
2012          1        2          3        5
2013          6        7          8        9
2014         16       17         18       19
2015         20       21         22       23

In [ ]:
b.unstack().stack()

/tmp/ipykernel_2951/725653305.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  b.unstack().stack().unstack()

       karachi                                            lahore            \
    avg_pakage                students                avg_pakage
          2012 2013 2014 2015     2012 2013 2014 2015       2012 2013 2014
cse          1    6   16   20        2    7   17   21          3    8   18
ece         16   20   21   43       17   21   23   54         18   22   23


         students
    2015     2012 2013 2014 2015
cse   22        5    9   19   23
ece   34       19   23   43   67

In [ ]:
b

            karachi              lahore
         avg_pakage students avg_pakage students
cse 2012          1        2          3        5
    2013          6        7          8        9
    2014         16       17         18       19
    2015         20       21         22       23
ece 2012         16       17         18       19
    2013         20       21         22       23
    2014         21       23         23       43
    2015         43       54         34       67

In [ ]:
#stack turn level 1 row into column(2)
b.stack().stack()

/tmp/ipykernel_2951/1997903416.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  b.stack().stack()

cse  2012  avg_pakage  karachi     1
                       lahore      3
           students    karachi     2
                       lahore      5
     2013  avg_pakage  karachi     6
                       lahore      8
           students    karachi     7
                       lahore      9
     2014  avg_pakage  karachi    16
                       lahore     18
           students    karachi    17
                       lahore     19
     2015  avg_pakage  karachi    20
                       lahore     22
           students    karachi    21
                       lahore     23
ece  2012  avg_pakage  karachi    16
                       lahore     18
           students    karachi    17
                       lahore     19
     2013  avg_pakage  karachi    20
                       lahore     22
           students    karachi    21
                       lahore     23
     2014  avg_pakage  karachi    21
                       lahore     23
           students    karachi    23
                       lahore     43
     2015  avg_pakage  karachi    43
                       lahore     34
           students    karachi    54
                       lahore     67
dtype: int64

In [ ]:
#unstack convert the level 1 column into row(2)
b.unstack().unstack()

karachi  avg_pakage  2012  cse     1
                           ece    16
                     2013  cse     6
                           ece    20
                     2014  cse    16
                           ece    21
                     2015  cse    20
                           ece    43
         students    2012  cse     2
                           ece    17
                     2013  cse     7
                           ece    21
                     2014  cse    17
                           ece    23
                     2015  cse    21
                           ece    54
lahore   avg_pakage  2012  cse     3
                           ece    18
                     2013  cse     8
                           ece    22
                     2014  cse    18
                           ece    23
                     2015  cse    22
                           ece    34
         students    2012  cse     5
                           ece    19
                     2013  cse     9
                           ece    23
                     2014  cse    19
                           ece    43
                     2015  cse    23
                           ece    67
dtype: int64

##Working with multiindex dataframe

In [ ]:
#head and tail
b.head()
#shape
b.shape
#info
b.info()
#duplicated
b.duplicated()
#isnull
b.isnull()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8 entries, ('cse', np.int64(2012)) to ('ece', np.int64(2015))
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (karachi, avg_pakage)  8 non-null      int64
 1   (karachi, students)    8 non-null      int64
 2   (lahore, avg_pakage)   8 non-null      int64
 3   (lahore, students)     8 non-null      int64
dtypes: int64(4)
memory usage: 932.0+ bytes

            karachi              lahore
         avg_pakage students avg_pakage students
cse 2012      False    False      False    False
    2013      False    False      False    False
    2014      False    False      False    False
    2015      False    False      False    False
ece 2012      False    False      False    False
    2013      False    False      False    False
    2014      False    False      False    False
    2015      False    False      False    False

##extraction from the multiindex data from

In [ ]:
b

            karachi              lahore
         avg_pakage students avg_pakage students
cse 2012          1        2          3        5
    2013          6        7          8        9
    2014         16       17         18       19
    2015         20       21         22       23
ece 2012         16       17         18       19
    2013         20       21         22       23
    2014         21       23         23       43
    2015         43       54         34       67

In [ ]:
#in naming index we use loc
#single row
b.loc[('cse',2015)]

karachi  avg_pakage    20
         students      21
lahore   avg_pakage    22
         students      23
Name: (cse, 2015), dtype: int64

In [ ]:
 #multiple rows
b.loc[('cse',2012):('ece',2014):2]

            karachi              lahore
         avg_pakage students avg_pakage students
cse 2012          1        2          3        5
    2014         16       17         18       19
ece 2012         16       17         18       19
    2014         21       23         23       43

In [ ]:
b

            karachi              lahore
         avg_pakage students avg_pakage students
cse 2012          1        2          3        5
    2013          6        7          8        9
    2014         16       17         18       19
    2015         20       21         22       23
ece 2012         16       17         18       19
    2013         20       21         22       23
    2014         21       23         23       43
    2015         43       54         34       67

In [ ]:
#fency indexing
#multiple rows by using iloc and numeric index
b.iloc[[2,5,7]]

            karachi              lahore
         avg_pakage students avg_pakage students
cse 2014         16       17         18       19
ece 2013         20       21         22       23
    2015         43       54         34       67

##extracting columns

In [ ]:
b['karachi']['students']

cse  2012     2
     2013     7
     2014    17
     2015    21
ece  2012    17
     2013    21
     2014    23
     2015    54
Name: students, dtype: int64

In [ ]:
b.iloc[:,1:3]

          karachi     lahore
         students avg_pakage
cse 2012        2          3
    2013        7          8
    2014       17         18
    2015       21         22
ece 2012       17         18
    2013       21         22
    2014       23         23
    2015       54         34

In [ ]:
b.iloc[[0,4],[1,2]]

          karachi     lahore
         students avg_pakage
cse 2012        2          3
ece 2012       17         18

In [ ]:
b

            karachi              lahore
         avg_pakage students avg_pakage students
cse 2012          1        2          3        5
    2013          6        7          8        9
    2014         16       17         18       19
    2015         20       21         22       23
ece 2012         16       17         18       19
    2013         20       21         22       23
    2014         21       23         23       43
    2015         43       54         34       67

In [ ]:
b.iloc[[0,],[0,3]]

            karachi   lahore
         avg_pakage students
cse 2012          1        5

##index sorting

In [ ]:
b.sort_index(ascending=False)
b.sort_index(ascending=[True,True])
b.sort_index(level=1,ascending=[False])

            karachi              lahore
         avg_pakage students avg_pakage students
cse 2015         20       21         22       23
ece 2015         43       54         34       67
cse 2014         16       17         18       19
ece 2014         21       23         23       43
cse 2013          6        7          8        9
ece 2013         20       21         22       23
cse 2012          1        2          3        5
ece 2012         16       17         18       19

In [ ]:
b.transpose()

                    cse                 ece
                   2012 2013 2014 2015 2012 2013 2014 2015
karachi avg_pakage    1    6   16   20   16   20   21   43
        students      2    7   17   21   17   21   23   54
lahore  avg_pakage    3    8   18   22   18   22   23   34
        students      5    9   19   23   19   23   43   67

In [184]:
#swap indexes
b.swaplevel()

            karachi              lahore
         avg_pakage students avg_pakage students
2012 cse          1        2          3        5
2013 cse          6        7          8        9
2014 cse         16       17         18       19
2015 cse         20       21         22       23
2012 ece         16       17         18       19
2013 ece         20       21         22       23
2014 ece         21       23         23       43
2015 ece         43       54         34       67

In [ ]:
#swap row indexes
b.swaplevel(axis=1)

         avg_pakage students avg_pakage students
            karachi  karachi     lahore   lahore
cse 2012          1        2          3        5
    2013          6        7          8        9
    2014         16       17         18       19
    2015         20       21         22       23
ece 2012         16       17         18       19
    2013         20       21         22       23
    2014         21       23         23       43
    2015         43       54         34       67

##Melt and pivot dataframe

In [ ]:
data=pd.DataFrame({'cse':[120,23,12,13]})
data.melt()

  variable  value
0      cse    120
1      cse     23
2      cse     12
3      cse     13

In [ ]:
#wide data
D1=pd.DataFrame({'cse':[130],'ece':[123], 'mach':[50]})
D1.melt(var_name='subject',value_name='num_students')

  subject  num_students
0     cse           130
1     ece           123
2    mach            50

In [ ]:
data=pd.DataFrame(
    {
      'branch':['cse','ece','mech','chemistry'],
      2012:[120,234,45,67],
      2014:[123,145,165,167],
      2015:[78,98,98,67]
    }
)
data.melt(id_vars=['branch'],var_name='year',value_name='num_student')

       branch  year  num_student
0         cse  2012          120
1         ece  2012          234
2        mech  2012           45
3   chemistry  2012           67
4         cse  2014          123
5         ece  2014          145
6        mech  2014          165
7   chemistry  2014          167
8         cse  2015           78
9         ece  2015           98
10       mech  2015           98
11  chemistry  2015           67

##Real world data set

In [174]:
confirm=pd.read_csv('/content/time_series_covid19_confirmed_global.csv')
death=pd.read_csv('/content/time_series_covid19_deaths_global - time_series_covid19_deaths_global.csv')

In [ ]:
death

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,7845,7846,7846,7846,7846,7847,7847,7849,7849,7849
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,3595,3595,3595,3595,3595,3595,3595,3595,3595,3595
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,6881,6881,6881,6881,6881,6881,6881,6881,6881,6881
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,165,165,165,165,165,165,165,165,165,165
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,1928,1928,1928,1930,1930,1930,1930,1930,1930,1930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,5708,5708,5708,5708,5708,5708,5708,5708,5708,5708
285,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
286,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,2159,2159,2159,2159,2159,2159,2159,2159,2159,2159
287,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,4019,4019,4022,4022,4023,4023,4024,4024,4024,4024
288,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,5637,5637,5637,5637,5637,5637,5637,5637,5637,5637

In [ ]:
death.shape

(289, 1081)

In [ ]:
death.tail()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
284,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,5708,5708,5708,5708,5708,5708,5708,5708,5708,5708
285,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
286,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,2159,2159,2159,2159,2159,2159,2159,2159,2159,2159
287,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,4019,4019,4022,4022,4023,4023,4024,4024,4024,4024
288,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,5637,5637,5637,5637,5637,5637,5637,5637,5637,5637

In [ ]:
confirm.shape

(289, 1081)

In [175]:
death=death.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='num_death')
death

,Province/State,Country/Region,Lat,Long,date,num_death
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0
...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,5708
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,0
311250,NaN,Yemen,15.552727,48.516388,1/2/23,2159
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,4024
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,5637

In [176]:
confirm=confirm.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='num_cases')

In [177]:
confirm

,Province/State,Country/Region,Lat,Long,date,num_cases
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0
...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,703228
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,535
311250,NaN,Yemen,15.552727,48.516388,1/2/23,11945
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,334661
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,259981

In [183]:
confirm.merge(death, on=['Province/State','Country/Region','Lat','Long','date'])[['Province/State','Country/Region',	'date','num_cases','num_death']]

       Province/State        Country/Region     date  num_cases  num_death
0                 NaN           Afghanistan  1/22/20          0          0
1                 NaN               Albania  1/22/20          0          0
2                 NaN               Algeria  1/22/20          0          0
3                 NaN               Andorra  1/22/20          0          0
4                 NaN                Angola  1/22/20          0          0
...               ...                   ...      ...        ...        ...
311248            NaN    West Bank and Gaza   1/2/23     703228       5708
311249            NaN  Winter Olympics 2022   1/2/23        535          0
311250            NaN                 Yemen   1/2/23      11945       2159
311251            NaN                Zambia   1/2/23     334661       4024
311252            NaN              Zimbabwe   1/2/23     259981       5637

[311253 rows x 5 columns]